[package]
name = "bf"
version = "2.0.0"
edition = "2021"
authors = ["Nick Lauri (https://github.com/nicklauri"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.17", features = ["derive"] }
